version : '3'
services:
  database:
    container_name: kubernetes-database
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123@qwe#
      - POSTGRES_DB=kubernetes-db
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/application-user.sql:/docker-entrypoint-initdb.d/2.sql"
    networks:
      - kubernetes-test

networks:
  kubernetes-test:
    external: false
    name: kubernetes-test