kind: Service
apiVersion: v1
metadata:
  namespace: kubernetes-lab
  name: study-kubernetes-node-port
  labels:
    app: study-kubernetes-uuid-node-service
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      nodePort: 32000
  selector:
    app: study-kubernetes-uuid-service