server:
  port: 9000

spring:
  application:
    name: study-kubernetes
  datasource:
    url: jdbc:postgresql://${DATABASE-HOST:localhost}:${DATABASE-PORT:5432}/kubernetes-db
    username: ${DATABASE-USER:root}
    password: ${DATABASE-PASSWORD:123@qwe#}
    poolName: kubernetes-pool
    maximum-pool-size: 10
    minimum-idle: 0
    idle-timeout: 60000
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

app:
  uuid-host: ${UUID-SERVICE-HOST:http://localhost:9200}