apiVersion: v1
kind: Service
metadata:
  namespace: kubernetes-lab
  name: study-kubernetes-postgres-external
  labels:
    app: study-kubernetes-postgres-external
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432